import React from "react";
import Banner from "../../layout/Banner/Banner";
import Head from "next/head";

import style from "./news.module.scss";
import { Container, Grid } from "@mui/material";

import data from "./data.json";
import Link from "next/link";

const News = () => {
  return (
    <>
      <Head>
        <title>News & Updates | GREENSHIFT NEPAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content="./1a3b9e8c-88a0-449a-8c74-0f58aef99fe6.png"
        />
        <meta property="og:image:width" content="640" />
        <meta property="og:image:height" content="442" />
      </Head>

      <Banner title={"News & Updates"} />

      <section className={style.newsList}>
        <Container maxWidth={"lg"}>
          <Grid container spacing={3}>
            {data.news.map((val, index) => {
              let link = val.title.toLowerCase().replace(/\s+/g, "-");

              return (
                <Grid item md={4} key={index}>
                  <div className={style.news_wrap}>
                    <div className={style.news_wrap_text}>
                      <h6>{val.title}</h6>

                      <span>{val.date}</span>

                      <div
                        className={style.news_wrap_text_description}
                        dangerouslySetInnerHTML={{ __html: val.text }}
                      />

                      <Link href={`/news-and-updates/${link}`}>Read More</Link>
                    </div>
                    <div className={style.news_wrap_image}>
                      <img src={val.image} alt="" />
                    </div>
                  </div>
                </Grid>
              );
            })}
          </Grid>
        </Container>
      </section>
    </>
  );
};

export default News;
