import { useState } from "react";
import Head from "next/head";
import Banner from "../../layout/Banner/Banner";

import style from "./style.module.scss";
import { Container } from "@mui/material";

import data from "./data.json";

const Quiz = () => {
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState("");

  const [answerChecked, setAnswerChecked] = useState(false);
  const [selectedAnswerIndex, setSelectedAnswerIndex] = useState(null);
  const [showResults, setShowResults] = useState(false);
  const [quizResult, setQuizResult] = useState({
    score: 0,
    correctAnswers: 0,
    wrongAnswers: 0,
  });

  const questions = data;

  const { question, image, answers, correctAnswer, review } =
    questions[currentQuestionIndex];

  const onAnswerSelected = (answer, idx) => {
    if (selectedAnswerIndex === null) {
      setAnswerChecked(true);
      setSelectedAnswerIndex(idx);
      setSelectedAnswer(answer);
    }
  };

  const handleNextQuestion = () => {
    if (selectedAnswer === correctAnswer) {
      setQuizResult((prev) => ({
        ...prev,
        score: prev.score + 5,
        correctAnswers: prev.correctAnswers + 1,
      }));
    } else {
      setQuizResult((prev) => ({
        ...prev,
        wrongAnswers: prev.wrongAnswers + 1,
      }));
    }
    if (currentQuestionIndex !== questions.length - 1) {
      setCurrentQuestionIndex((prev) => prev + 1);
    } else {
      setShowResults(true);
    }
    setSelectedAnswer("");
    setSelectedAnswerIndex(null);
    setAnswerChecked(false);
  };

  return (
    <>
      <Head>
        <title>Quiz | GREENSHIFT NEPAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content="./1a3b9e8c-88a0-449a-8c74-0f58aef99fe6.png"
        />
        <meta property="og:image:width" content="640" />
        <meta property="og:image:height" content="442" />
      </Head>

      <Banner title={"Plastic Pollution Quiz"} />

      <div className={style.wrapper}>
        <div className={style.quiz_title}>
          <Container maxWidth={"md"}>
            <h2>Plastic Pollution Quiz</h2>

            <p>
              How much do you know about the threats that our planet faces from
              plastic pollution?
            </p>
          </Container>
        </div>

        <Container maxWidth="md">
          {!showResults ? (
            <>
              <div className={style.question}>
                <h4>{question}</h4>

                <img src={image} alt="" />
              </div>

              <div className={style.options_wrap}>
                {answers.map((answer, idx) => {
                  return (
                    <div
                      className={`${style.option} ${
                        selectedAnswerIndex === idx
                          ? answer === correctAnswer
                            ? style.correct
                            : style.incorrect
                          : selectedAnswer && answer === correctAnswer
                          ? style.correct
                          : ""
                      }`}
                      key={idx}
                      onClick={() => onAnswerSelected(answer, idx)}
                    >
                      <span></span>
                      <p>{answer}</p>
                    </div>
                  );
                })}
              </div>

              {answerChecked ? (
                <>
                  <div className={style.answer_review}>
                    <h5>Correct</h5>
                    <div
                      className={style.text}
                      dangerouslySetInnerHTML={{
                        __html: review,
                      }}
                    />
                  </div>

                  <div className={style.next_step}>
                    <button
                      onClick={handleNextQuestion}
                      disabled={!answerChecked}
                    >
                      Continue
                    </button>
                  </div>
                </>
              ) : (
                ""
              )}
            </>
          ) : (
            "Result"
          )}
        </Container>
      </div>
    </>
  );
};

export default Quiz;
