import Banner from "../../layout/Banner/Banner";
import Head from "next/head";

import style from "./style.module.scss";
import { Container, Grid } from "@mui/material";
const Reports = () => {
  return (
    <>
      <Head>
        <title>Publications & Reports | GREENSHIFT NEPAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content="./1a3b9e8c-88a0-449a-8c74-0f58aef99fe6.png"
        />
        <meta property="og:image:width" content="640" />
        <meta property="og:image:height" content="442" />
      </Head>

      <Banner parent={"Knowledge Hub"} title={"Publications & Reports"} />

      <section className={style.report_wrap}>
        <Container maxWidth="lg">
          <Grid container spacing={4}>
            <Grid item md={3}>
              <div className={style.report_card}>
                <a
                  href="/GREEN SHIFT KICK OFF EVENT REPORT.pdf"
                  target="_blank"
                >
                  <img src="/GREEN SHIFT KICK OFF EVENT REPORT 1.jpg" alt="" />

                  <h5>GREEN SHIFT KICK OFF EVENT REPORT</h5>
                </a>
              </div>
            </Grid>
          </Grid>
        </Container>
      </section>
    </>
  );
};

export default Reports;
