import React from "react";

import Head from "next/head";

import VerticalScroll from "@/components/VerticalScroll";
import HorizontalScroll from "@/components/HorizontalScroll";
import { Container, Grid } from "@mui/material";

import BannerWave from "../components/BannerCurve";
import HomeFocusArea from "../components/HomeFocusArea";

import useSnoothScroll from "@/hook/use-smooth-scroll";

import homeStyle from "@/styles/home.module.scss";

export default function Home() {
  useSnoothScroll();
  return (
    <>
      <Head>
        <title>GREENSHIFT NEPAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={homeStyle.hero}>
        <video autoPlay loop muted>
          <source src="./intro.mp4" type="video/mp4" />
        </video>
        <Container maxWidth="xl">
          <div className={homeStyle.text}>
            <h1>Circularity of Plastic Waste</h1>

            <p>
              Promoting circular economy of plastics by effectively working
              towards minimizing plastic waste and diverting existing waste into
              product value chain.
            </p>
          </div>
        </Container>
      </section>

      <section className={homeStyle.intro} id="intro">
        {/* <div className={homeStyle.curve}>
          <BannerWave fill="#fff" />
        </div> */}

        <Container maxWidth="lg">
          <Grid container alignItems={"center"} spacing={10}>
            <Grid item sm={6} id="introText">
              <h2>About Us</h2>
              <p>
                Green Shift: Circularity of Plastic Waste for Net-Zero Carbon
                Nepal (GreenShift Nepal) project is funded by the European Union
                to promote a just transition to circular economy. GreenShift
                Nepal is a four-year project which will be implemented in 9
                municipalities – 3 in each of Bagmati, Madhesh, and Lumbini
                provinces.
              </p>
              <p>
                The project implementation is led by <strong>CREASION</strong>{" "}
                through the consortium partners
                <strong> Restless Development</strong>, and{" "}
                <strong>Youth Innovation Lab</strong>.
              </p>
            </Grid>

            <Grid item sm={6}>
              <video autoPlay loop muted>
                <source src="./SDG goals GS.mp4" type="video/mp4" />
              </video>
            </Grid>
          </Grid>
        </Container>
      </section>

      <section className={homeStyle.focus_area}>
        {/* <div className={homeStyle.curve}>
              <Wave fill="#1e607a" />
            </div> */}

        <Container maxWidth="lg">
          <h2 style={{ textAlign: "center" }}>Focus Areas</h2>

          <Container maxWidth="sm" style={{ textAlign: "center" }}>
            <p>
              GreenShift Nepal will work with waste enterprises, SMEs, CSOs of
              waste workers, youths, school children, and three tiers of
              government in the promotion of circular economy of plastics.
            </p>
          </Container>
        </Container>

        <div className={homeStyle.focusBox}>
          <HomeFocusArea />
        </div>
      </section>

      <Container maxWidth="lg">
        {/* <VerticalScroll /> */}

        {/* <HorizontalScroll /> */}
      </Container>
    </>
  );
}
